version: "3.7"

networks:
  network:
    driver: bridge

services:

  target: 
    build: ansible-target
    image: ansible-target 
    container_name: ansible-target
    image: ansible-target
    networks:
      - network
    volumes:
      - ./artifacts:/artifacts
    ports:
      - 6080:80
      - 6443:443
    privileged: true

  controller:
    build: ansible-controller
    image: ansible-controller 
    depends_on:
      - target
    container_name: ansible-controller
    image: ansible-controller
    networks:
      - network
    volumes:
      - ./playbooks:/playbooks
    tty: true