---
- hosts: servers
  tasks:

    - name: Install httpd package
      become: true
      yum:
        name: httpd
        state: latest
      
    - name: Create apache user
      become: true
      user:
        name: apache
        uid: 2001
        home: /home/apache
        shell: /bin/bash

    - name: Set permissions on server configuration
      become: true
      file: 
        dest: /etc/httpd
        owner: apache
        group: apache
        mode: u=rwx,g=rwx,o=r
        recurse: yes

    - name: Set permissions on web content
      become: true
      file: 
        dest: /var/www/html
        owner: apache
        group: apache
        mode: u=rwx,g=rwx,o=rx
        recurse: yes

    - name: Check if default welcome page exists
      become: true
      become_user: apache
      stat: 
        path: /etc/httpd/conf.d/welcome.conf
      register: welcome_page

    - name: Disable default welcome page
      become: true
      become_user: apache
      when: welcome_page.stat.exists
      copy:
        remote_src: yes
        src: /etc/httpd/conf.d/welcome.conf
        dest: /etc/httpd/conf.d/welcome.conf.disabled

    - name: Create custom welcome page
      become: true
      become_user: apache
      copy:
        dest: /var/www/html/index.html
        content: <h1>This page was generated by Ansible!</h1>

    - name: Make sure a service is running
      become: true
      systemd:
        state: started
        name: httpd