---
- hosts: servers
  tasks:

    - name: Install httpd package
      become: true
      yum:
        name: httpd
        state: latest
      
    - name: Create apache user
      become: true
      user:
        name: apache
        uid: 2001
        home: /home/apache
        shell: /bin/bash

    - name: Set permissions on server configuration
      become: true
      file: 
        dest: /etc/httpd
        owner: apache
        group: apache
        mode: u=rwx,g=rwx,o=r
        recurse: yes

    - name: Set permissions on web content
      become: true
      file: 
        dest: /var/www/html
        owner: apache
        group: apache
        mode: u=rwx,g=rwx,o=rx
        recurse: yes

    - name: Check if default welcome page exists
      become: true
      become_user: apache
      stat: 
        path: /etc/httpd/conf.d/welcome.conf
      register: welcome_page

    - name: Disable default welcome page
      become: true
      become_user: apache
      when: welcome_page.stat.exists
      copy:
        remote_src: yes
        src: /etc/httpd/conf.d/welcome.conf
        dest: /etc/httpd/conf.d/welcome.conf.disabled

    - name: Create custom welcome page
      become: true
      become_user: apache
      copy:
        dest: /var/www/html/index.html
        content: <h1>This page was generated by Ansible!</h1>

    - name: Make sure a service is running
      become: true
      systemd:
        state: started
        name: httpd

#             1  python3
#     2  yum install python3
#     3  sudo python3 -m venv /opt/jupyterhub/
#     4  python3 -m venv /opt/jupyterhub/
#     5  /opt/jupyterhub/bin/python3 -m pip install wheel jupyterhub jupyterlab ipywidgets
#     6  /opt/jupyterhub/bin/python3 -m pip install wheel
#     7  /opt/jupyterhub/bin/pip3 install --upgrade pip
#     8  /opt/jupyterhub/bin/python3 -m pip install wheel
#     9  /opt/jupyterhub/bin/python3 -m pip install jupyterhub
#    10  /opt/jupyterhub/bin/python3 -m pip install jupyterhub
#    11  /opt/jupyterhub/bin/python3 -m pip install jupyterlab
#    12  /opt/jupyterhub/bin/python3 -m pip install ipywidgets
#    13  yum install nodejs
#    14  curl https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh | bash
#    15  source ~/.bashrc 
#    16  nvm --version
#    17  nvm use 14
#    18  nvm install 14
#    19  npm install -g configurable-http-proxy
#    20  mkdir -p /opt/jupyterhub/etc/jupyterhub/
#    21  cd /opt/jupyterhub/etc/jupyterhub/
#    22  /opt/jupyterhub/bin/jupyterhub --generate-config
#    23  history
#    24  cat /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
#    25  wc -l /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
#    26  head -500 /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
#    27  cat /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
#    28  echo "c.Spawner.default_url = '/lab'" > /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
#    29  cat /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
#    30  mkdir -p /opt/jupyterhub/etc/systemd
#    31  cat << EOF > /opt/jupyterhub/etc/systemd/jupyterhub.service
# [Unit]
# Description=JupyterHub
# After=syslog.target network.target

# [Service]
# User=root
# Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/jupyterhub/bin"
# ExecStart=/opt/jupyterhub/bin/jupyterhub -f /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py

# [Install]
# WantedBy=multi-user.target
# EOF

#    32  cat /opt/jupyterhub/etc/systemd/jupyterhub.service
#    33  ln -s /opt/jupyterhub/etc/systemd/jupyterhub.service /etc/systemd/system/jupyterhub.service
#    34  systemctl daemon-reload
#    35  systemctl enable jupyterhub.service
#    36  systemctl start jupyterhub.service
#    37  systemctl status jupyterhub.service
#    38  systemctl status jupyterhub.service
#    39  history


# export CONFIGURABLE_HTTP_PROXY=$(nvm which default | sed "s/node$/configurable-http-proxy/")
# echo "c.ConfigurableHTTPProxy.command = '$CONFIGURABLE_HTTP_PROXY'" >> /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py