---
- hosts: servers
  tasks:

    - name: Install Python 3
      become: true
      yum:
        name: 
          - python3
        state: latest
    
    - name: Check if NodeJs repos is set up
      become: true
      shell: yum repolist | { grep nodesource || true; }
      register: nodejs_repo
      changed_when: nodejs_repo.stdout_lines|length < 1
      args: 
        warn: false

    - name: Set up NodeJs package repository
      when: nodejs_repo.changed
      become: true
      script: /playbooks/install_node.sh

    - name: Install NodeJs
      when: nodejs_repo.changed
      become: true
      yum:
        name: 
          - nodejs
        state: latest

    - name: Check if HTTP proxy is installed
      shell: npm list -g | { grep configurable-http-proxy || true; }
      register: http_proxy_installed
      changed_when: http_proxy_installed.stdout_lines|length < 1

    - name: Install NodeJs HTTP proxy
      when: http_proxy_installed.changed
      become: true
      command: npm install -g configurable-http-proxy

    - name: Create jupyter user
      become: true
      user:
        name: jupyter
        uid: 2001
        home: /home/jupyter
        shell: /bin/bash
    
    - name: Set permissions for Jupyter Hub installation directory
      become: true
      file: 
        dest: /opt/jupyterhub
        state: directory
        owner: jupyter
        group: jupyter
        mode: u=rwx,g=rwx,o=r
        recurse: yes
      
    - name: Check if Python packages are installed
      become: true
      become_user: jupyter
      shell: /opt/jupyterhub/bin/python3 -m pip list | { grep -E "(wheel |jupyterhub |jupyterlab |ipywidgets )" || true; }
      register: python_packages_installed
      changed_when: python_packages_installed.stdout_lines|length < 1

    - name: Create python dependency installation script
      when: python_packages_installed.changed
      become: true
      copy:
        dest: /install.sh
        content: |
          set -e
          python3 -m venv /opt/jupyterhub/
          /opt/jupyterhub/bin/python3 -m pip install --upgrade pip
          /opt/jupyterhub/bin/python3 -m pip install wheel
          /opt/jupyterhub/bin/python3 -m pip install jupyterhub
          /opt/jupyterhub/bin/python3 -m pip install jupyterlab
          /opt/jupyterhub/bin/python3 -m pip install ipywidgets
    
    - name: Make installation script executable
      when: python_packages_installed.changed
      become: true
      file:
        dest: /install.sh
        mode: u=rwx,g=rwx,o=r
        owner: jupyter
    
    - name: Execute python dependency installation script
      when: python_packages_installed.changed
      become_user: jupyter
      become: true
      shell: bash /install.sh
      register: installation

    - debug: var=installation.stdout_lines
      when: python_packages_installed.changed

    - name: Create configuration folder
      become_user: jupyter
      become: true
      file: 
        dest: /opt/jupyterhub/etc/jupyterhub
        state: directory

    - name: Create configuration file
      become_user: jupyter
      become: true
      copy:
        dest: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
        content: |
          c.Spawner.default_url = '/lab'
          c.JupyterHub.port = 80

    - name: Create system service diretory
      become_user: jupyter
      become: true
      file:
        dest: /opt/jupyterhub/etc/systemd
        state: directory

    - name: Create system service configuration
      become_user: jupyter
      become: true
      copy:
        dest: /opt/jupyterhub/etc/systemd/jupyterhub.service
        content: |
          [Unit]
          Description=JupyterHub
          After=syslog.target network.target

          [Service]
          User=root
          Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/jupyterhub/bin"
          ExecStart=/opt/jupyterhub/bin/jupyterhub -f /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py

          [Install]
          WantedBy=multi-user.target
    
    - name: Symlink system service configuration
      become: true
      file: 
        src: /opt/jupyterhub/etc/systemd/jupyterhub.service
        dest: /etc/systemd/system/jupyterhub.service
        state: link

    - name: Create Jupyter Hub administration command alias
      become: true
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'Cmnd_Alias JUPYTERHUB_ADMIN = /usr/bin/systemctl start jupyterhub.service, /usr/bin/systemctl stop jupyterhub.service'

    - name: Grant system rights to jupyter user
      become: true
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'jupyter ALL=(ALL) NOPASSWD: JUPYTERHUB_ADMIN'

    - name: Start service
      become: true
      systemd:
        name: jupyterhub
        enabled: true
        daemon_reload: true
        state: started